class DataWareHouse{
    List<String> jobTitles = [
      "Sales Executive/Officer",
      "Technical Architect",
      "Associate/Senior Associate -(Technical)",
      "Corporate Planning/Strategy Manager",
      "Webmaster",
      "Process Flow Analyst",
      "Software Developer",
      "Social Media Marketing Manager",
      "Senior Design Engineer",
      "Accounts Manager",
      "Sales Officer",
      "Sales/Business Development Manager",
      "Quality Assurance/Quality Control Executive",
      "Graphic/Web Designer",
      "Area Sales Manager",
      "System Administrator",
      "Project Manager-IT/Software",
      "Project Lead",
      "Logistics Executive",
      "Accounts Executive/Accountant",
      "Associate/Senior Associate -(NonTechnical)",
      "Technical Support Manager",
      "Regional Manager",
      "Head / VP/ GM/ National Manager After Sales",
      "DBA",
      "HR Executive",
      "Head/VP/GM/National Manager -Sales",
      "Centre Head / Branch Head / Club Manager",
      "Project Architect",
      "Design Engineer",
      "Technical Writer",
      "Engineering Manager",
      "Training Manager",
      "Trainee",
      "Search Engine Optimisation /SEO Specialist",
      "Financial Analyst",
      "PPC /Pay Per Click Specialist",
      "Medical Representative",
      "Project Manager-Production/Manufacturing/Maintenance",
      "Public Relations & Media Relations Manager",
      "Fresher",
      "Lecturer/Professor",
      "Documentation/Medical Writing",
      "IT/Networking-Manager",
      "Sales Trainer",
      "Client Servicing Executive",
      "Sales Coordinator",
      "Solution Architect / Enterprise Architect",
      "Workman/Foreman/Technician",
      "Design Engineer/Manager",
      "Technical Lead/Project Lead",
      "Team Leader -(NonTechnical)",
      "Analytics Manager",
      "Accounts Executive/Accountant",
      "Visualiser",
      "Creative Director",
      "Outside Consultant",
      "Purchase Executive",
      "Telecalling/Telemarketing Executive",
      "Cashier",
      "Software Developer",
      "Other",
      "Voice & Accent Trainer",
      "Finance/Budgeting Manager",
      "Outside Technical Consultant",
      "CSR Manager",
      "Surgeon",
      "Software Developer",
      "Nurse",
      "Direct Marketing Executive",
      "Customer Support Engineer/Technician",
      "Data Analyst",
      "Service/Maintenance Engineer",
      "Tour Management Manager/Senior Manager",
      "Maintenance Engineer",
      "Branch Manager",
      "Account Manager",
      "Research Scientist",
      "Quality Assurance/Quality Control Manager",
      "Graphic Designer",
      "Technical Support Engineer"
    ];
}