"""Recommender System - Collaborative Filtering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yi-Uw5RABrHVa26myn-OMh3SCycas2Mv
"""

import pandas as pd

def get_movie_matrix():

    column_names = ['user_id', 'item_id', 'rating', 'timestamp']
    
    path = 'dataset/file.tsv'
    df = pd.read_csv(path, sep='\t', names=column_names)

    movie_titles = pd.read_csv('dataset/movies_title.csv')
    
    data = pd.merge(df, movie_titles, on='item_id')
    data.groupby('title')['rating'].mean().sort_values(ascending=False).head()
    data.groupby('title')['rating'].count().sort_values(ascending=False).head()

    ratings = pd.DataFrame(data.groupby('title')['rating'].mean())
    ratings['num of ratings'] = pd.DataFrame(data.groupby('title')['rating'].count())
    ratings.head()

    moviemat = data.pivot_table(index ='user_id',
                columns ='title', values ='rating')


    return moviemat,ratings
